# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ReportingCenter(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, reporting_center_context: str=None, reporting_center_id: str=None):
        """
        ReportingCenter - a model defined in Swagger

        :param reporting_center_context: The reporting_center_context of this ReportingCenter.
        :type reporting_center_context: str
        :param reporting_center_id: The reporting_center_id of this ReportingCenter.
        :type reporting_center_id: str
        """
        self.swagger_types = {
            'reporting_center_context': str,
            'reporting_center_id': str
        }

        self.attribute_map = {
            'reporting_center_context': 'reporting_center_context',
            'reporting_center_id': 'reporting_center_id'
        }

        self._reporting_center_context = reporting_center_context
        self._reporting_center_id = reporting_center_id

    @classmethod
    def from_dict(cls, dikt) -> 'ReportingCenter':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReportingCenter of this ReportingCenter.
        :rtype: ReportingCenter
        """
        return deserialize_model(dikt, cls)

    @property
    def reporting_center_context(self) -> str:
        """
        Gets the reporting_center_context of this ReportingCenter.

        :return: The reporting_center_context of this ReportingCenter.
        :rtype: str
        """
        return self._reporting_center_context

    @reporting_center_context.setter
    def reporting_center_context(self, reporting_center_context: str):
        """
        Sets the reporting_center_context of this ReportingCenter.

        :param reporting_center_context: The reporting_center_context of this ReportingCenter.
        :type reporting_center_context: str
        """

        self._reporting_center_context = reporting_center_context

    @property
    def reporting_center_id(self) -> str:
        """
        Gets the reporting_center_id of this ReportingCenter.

        :return: The reporting_center_id of this ReportingCenter.
        :rtype: str
        """
        return self._reporting_center_id

    @reporting_center_id.setter
    def reporting_center_id(self, reporting_center_id: str):
        """
        Sets the reporting_center_id of this ReportingCenter.

        :param reporting_center_id: The reporting_center_id of this ReportingCenter.
        :type reporting_center_id: str
        """

        self._reporting_center_id = reporting_center_id

