# coding: utf-8

from __future__ import absolute_import
from pyhml.models.sbt_ngs import SbtNgs
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class TypingMethod(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, sbt_ngs: SbtNgs=None):
        """
        TypingMethod - a model defined in Swagger

        :param sbt_ngs: The sbt_ngs of this TypingMethod.
        :type sbt_ngs: SbtNgs
        """
        self.swagger_types = {
            'sbt_ngs': SbtNgs
        }

        self.attribute_map = {
            'sbt_ngs': 'sbt_ngs'
        }

        self._sbt_ngs = sbt_ngs

    @classmethod
    def from_dict(cls, dikt) -> 'TypingMethod':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TypingMethod of this TypingMethod.
        :rtype: TypingMethod
        """
        return deserialize_model(dikt, cls)

    @property
    def sbt_ngs(self) -> SbtNgs:
        """
        Gets the sbt_ngs of this TypingMethod.

        :return: The sbt_ngs of this TypingMethod.
        :rtype: SbtNgs
        """
        return self._sbt_ngs

    @sbt_ngs.setter
    def sbt_ngs(self, sbt_ngs: SbtNgs):
        """
        Sets the sbt_ngs of this TypingMethod.

        :param sbt_ngs: The sbt_ngs of this TypingMethod.
        :type sbt_ngs: SbtNgs
        """

        self._sbt_ngs = sbt_ngs

