# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class VariantEffect(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, term: str=None):
        """
        VariantEffect - a model defined in Swagger

        :param term: The term of this VariantEffect.
        :type term: str
        """
        self.swagger_types = {
            'term': str
        }

        self.attribute_map = {
            'term': 'term'
        }

        self._term = term

    @classmethod
    def from_dict(cls, dikt) -> 'VariantEffect':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VariantEffect of this VariantEffect.
        :rtype: VariantEffect
        """
        return deserialize_model(dikt, cls)

    @property
    def term(self) -> str:
        """
        Gets the term of this VariantEffect.

        :return: The term of this VariantEffect.
        :rtype: str
        """
        return self._term

    @term.setter
    def term(self, term: str):
        """
        Sets the term of this VariantEffect.

        :param term: The term of this VariantEffect.
        :type term: str
        """

        self._term = term

